#
# This workflow calls the main distribution pipeline from DuckDB to build, test and (optionally) release the extension
#
name: Main Extension Distribution Pipeline
on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      extension_name:
        description: 'The name with which the extension will be built'
        required: false
        type: string
        default: extension_alias

      extension_canonical:
        description: 'If this is an alias extension, the name of the canonical extension'
        required: false
        type: string
        default: nanoarrow

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true

env:
  RUN_TEST: 1
  
jobs:
  duckdb-build:
    name: Build extension binaries
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_distribution.yml@main
    with:
      duckdb_version: v1.2.2
      ci_tools_version: v1.2.2
      extension_name: ${{github.event.inputs.extension_name }}
      extension_canonical: ${{github.event.inputs.extension_canonical }}
      extra_toolchains: python3

