#
# This workflow calls the main distribution pipeline from DuckDB to build, test and (optionally) release the extension
#
name: Main Extension Distribution Pipeline
on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true

env:
  RUN_TEST: 1
  EXTENSION_NAME: "arrow"
  EXTENSION_WRAPPER_NAME: "nanoarrow"
  
jobs:
  duckdb-build:
    name: Build extension binaries
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_distribution.yml@v1.2.2
    with:
      duckdb_version: v1.2.2
      ci_tools_version: v1.2.2
      extension_name: ${{ env.EXTENSION_NAME }}
      extra_toolchains: python3
      extension_wrapper_name: ${{ env.EXTENSION_WRAPPER_NAME }}